#!/usr/bin/env bash
# CI 用: 環境変数 YELLME_CLAUDE_API_KEY があれば Secrets.swift を上書き生成する。
# シェル展開でキーを壊さないよう Python でエスケープする。
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${ROOT}/Sources/Core/Services/Secrets.swift"

if [[ -z "${YELLME_CLAUDE_API_KEY:-}" ]]; then
  echo "YELLME_CLAUDE_API_KEY unset — skipping Secrets.swift generation."
  exit 0
fi

export WRITE_SECRETS_ROOT="$ROOT"
python3 <<'PY'
import os
from pathlib import Path

key = os.environ.get("YELLME_CLAUDE_API_KEY", "").strip()
if not key:
    raise SystemExit(0)

root = Path(os.environ["WRITE_SECRETS_ROOT"])
dest = root / "Sources/Core/Services/Secrets.swift"

def swift_string_literal(s: str) -> str:
    escaped = (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )
    return f'"{escaped}"'

body = (
    "// Generated by scripts/write-secrets-from-env.sh — do not commit.\n"
    "enum Secrets {\n"
    f"    static let claudeAPIKey = {swift_string_literal(key)}\n"
    "}\n"
)
dest.write_text(body, encoding="utf-8")
print(f"Wrote {dest} from YELLME_CLAUDE_API_KEY.")
PY
